version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecurepass
      - POSTGRES_DB=rails-k8s-docker-demo_development
      - PGDATA=/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - ./tmp/redis:/data      

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_SERVER=redis://redis:6379/0
      - FORWARD_SERVER=http://host.docker.internal:3001
